<h2>Create and Print Numpy Array

In [2]:
import numpy as np


In [12]:
first_numpy_array=np.array([1,9,4,6,5,7,8,2])

In [14]:
first_numpy_array
print first_numpy_array

[1 9 4 6 5 7 8 2]


In [18]:
array_with_zeros=np.zeros((3,3))


In [19]:
print array_with_zeros

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [23]:
array_with_one=np.ones((3,3))
array_with_one

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
array_with_empty=np.empty((3,3))
array_with_empty

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
print array_with_empty

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [31]:
array_arange=np.arange(12)
print array_arange

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [43]:
OD_array=np.arange(12)

In [44]:
print OD_array

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
TD_array=OD_array.reshape(3,4)

In [46]:
TD_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])