In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [2]:
iris_df=pd.read_csv("Iris.csv")

In [3]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
label_encoder=preprocessing.LabelEncoder()

In [6]:
iris_df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [7]:
#iris_df[""].unique()

In [8]:
iris_df["species"]=label_encoder.fit_transform(iris_df["species"])

In [9]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [10]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [11]:
from sklearn import datasets
from sklearn.preprocessing import OneHotEncoder

In [12]:
iris_data=datasets.load_iris()

In [13]:
#iris_data

In [14]:
iris_data=pd.DataFrame(data=np.c_[iris_data["data"],iris_data["target"]], columns=iris_data["feature_names"]+["target"])


In [15]:
y=iris_data.target.values

In [16]:
y


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [17]:
iris_data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [18]:
iris_data.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0

In [19]:
onehotencoder = OneHotEncoder(categories='auto')
y=onehotencoder.fit_transform(y.reshape(-1,1))


In [20]:
print(y.toarray())

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [21]:
pd.get_dummies(iris_data.target).head()

0.0  1.0  2.0
0    1    0    0
1    1    0    0
2    1    0    0
3    1    0    0
4    1    0    0

In [22]:
from sklearn.feature_extraction import FeatureHasher

In [23]:
game_df=pd.read_csv("vgsales.csv",encoding="utf-8")

In [24]:
game_df.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [25]:
game_df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [26]:
game_df.shape


(16598, 11)

In [27]:
game_df[['Name', 'Platform', 'Year', 'Genre']].iloc[1:7]

Name Platform    Year         Genre
1         Super Mario Bros.      NES  1985.0      Platform
2            Mario Kart Wii      Wii  2008.0        Racing
3         Wii Sports Resort      Wii  2009.0        Sports
4  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing
5                    Tetris       GB  1989.0        Puzzle
6     New Super Mario Bros.       DS  2006.0      Platform

In [28]:
game_df[['Name', 'Platform', 'Genre']].iloc[1:7]

Name Platform         Genre
1         Super Mario Bros.      NES      Platform
2            Mario Kart Wii      Wii        Racing
3         Wii Sports Resort      Wii        Sports
4  Pokemon Red/Pokemon Blue       GB  Role-Playing
5                    Tetris       GB        Puzzle
6     New Super Mario Bros.       DS      Platform

In [29]:
u_generes = np.unique(game_df["Genre"])

In [30]:
print("Total no of genre : ", len(u_generes))
u_generes

Total no of genre :  12


array(['Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy'], dtype=object)

In [31]:
fh=FeatureHasher(n_features=6,input_type="string")
hasted_features=fh.fit_transform(game_df['Genre'])
hasted_features=hasted_features.toarray()


In [32]:
new_game_df=pd.concat([game_df[["Name","Genre"]],pd.DataFrame(hasted_features)],axis=1)

new_game_df.head(10)

Name         Genre    0    1    2    3    4    5
0                 Wii Sports        Sports -2.0  2.0  0.0 -2.0  0.0  0.0
1          Super Mario Bros.      Platform  0.0  2.0  2.0 -1.0  1.0  0.0
2             Mario Kart Wii        Racing -1.0  0.0  0.0  0.0  0.0 -1.0
3          Wii Sports Resort        Sports -2.0  2.0  0.0 -2.0  0.0  0.0
4   Pokemon Red/Pokemon Blue  Role-Playing -1.0  1.0  2.0  0.0  1.0 -1.0
5                     Tetris        Puzzle  0.0  1.0  1.0 -2.0  1.0 -1.0
6      New Super Mario Bros.      Platform  0.0  2.0  2.0 -1.0  1.0  0.0
7                   Wii Play          Misc  0.0  0.0  0.0 -2.0  1.0 -1.0
8  New Super Mario Bros. Wii      Platform  0.0  2.0  2.0 -1.0  1.0  0.0
9                  Duck Hunt       Shooter -1.0  4.0  0.0 -1.0  0.0 -1.0

In [33]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline



In [35]:
df=pd.read_csv("dataset.csv")
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [36]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [37]:
df.shape

(1470, 35)

In [38]:
df.isna().sum(axis=0)

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

In [42]:
for i in df.columns:
    print(i, " : ", df[i].value_counts())
    print("\n")
    print(" = "*40)
    print("\n")

Age  :  35    78
34    77
36    69
31    69
29    68
32    61
30    60
33    58
38    58
40    57
37    50
27    48
28    48
42    46
39    42
45    41
41    40
26    39
44    33
46    33
43    32
50    30
25    26
24    26
49    24
47    24
55    22
51    19
53    19
48    19
54    18
52    18
22    16
56    14
23    14
58    14
21    13
20    11
59    10
19     9
18     8
60     5
57     4
Name: Age, dtype: int64


 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 


Attrition  :  No     1233
Yes     237
Name: Attrition, dtype: int64


 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 


BusinessTravel  :  Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: BusinessTravel, dtype: int64


 =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 


DailyR

In [44]:
for i in df.columns:
    print(i," : ",df[i].unique())
    print("\n")

Age  :  [41 49 37 33 27 32 59 30 38 36 35 29 31 34 28 22 53 24 21 42 44 46 39 43
 50 26 48 55 45 56 23 51 40 54 58 20 25 19 57 52 47 18 60]


Attrition  :  ['Yes' 'No']


BusinessTravel  :  ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']


DailyRate  :  [1102  279 1373 1392  591 1005 1324 1358  216 1299  809  153  670 1346
  103 1389  334 1123 1219  371  673 1218  419  391  699 1282 1125  691
  477  705  924 1459  125  895  813 1273  869  890  852 1141  464 1240
 1357  994  721 1360 1065  408 1211 1229  626 1434 1488 1097 1443  515
  853 1142  655 1115  427  653  989 1435 1223  836 1195 1339  664  318
 1225 1328 1082  548  132  746  776  193  397  945 1214  111  573 1153
 1400  541  432  288  669  530  632 1334  638 1093 1217 1353  120  682
  489  807  827  871  665 1040 1420  240 1280  534 1456  658  142 1127
 1031 1189 1354 1467  922  394 1312  750  441  684  249  841  147  528
  594  470  957  542  802 1355 1150 1329  959 1033 1316  364  438  689
  201 1427  857  933 1181 1395  6

In [45]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [46]:
df=df.drop(['Over18','EmployeeNumber','EmployeeCount','StandardHours'],axis=1)

In [47]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [48]:
df.shape

(1470, 31)

In [49]:
df[['RelationshipSatisfaction','JobSatisfaction','EnvironmentSatisfaction','JobInvolvement']]

RelationshipSatisfaction  JobSatisfaction  EnvironmentSatisfaction  \
0                            1                4                        2   
1                            4                2                        3   
2                            2                3                        4   
3                            3                3                        4   
4                            4                2                        1   
...                        ...              ...                      ...   
1465                         3                4                        3   
1466                         1                1                        4   
1467                         2                2                        2   
1468                         4                2                        4   
1469                         1                3                        2   

      JobInvolvement  
0                  3  
1                  2  
2                  2  
3                  3  
4                  3  
...              ...  
1465               4  
1466               2  
1467               4  
1468               2  
1469               4  

[1470 rows x 4 columns]

In [50]:
df["TotalSatisfaction mean"]=(df['RelationshipSatisfaction']+df['JobSatisfaction']+df['EnvironmentSatisfaction']+df['JobInvolvement']+df['WorkLifeBalance'])/5

In [51]:
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                 1          2  Life Sciences                        2   
1                 8          1  Life Sciences                        3   
2                 2          2          Other                        4   
3                 3          4  Life Sciences                        4   
4                 2          1        Medical                        1   

   Gender  ...  RelationshipSatisfaction  StockOptionLevel  TotalWorkingYears  \
0  Female  ...                         1                 0                  8   
1    Male  ...                         4                 1                 10   
2    Male  ...                         2                 0                  7   
3  Female  ...                         3                 0                  8   
4    Male  ...                         4                 1                  6   

  TrainingTimesLastYear  WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                     0                1              6                   4   
1                     3                3             10                   7   
2                     3                3              0                   0   
3                     3                3              8                   7   
4                     3                3              2                   2   

   YearsSinceLastPromotion  YearsWithCurrManager TotalSatisfaction mean  
0                        0                     5                    2.2  
1                        1                     7                    2.8  
2                        0                     0                    2.8  
3                        3                     0                    3.2  
4                        2                     2                    2.6  

[5 rows x 32 columns]

In [53]:
def Satif(df):
    if df['TotalSatisfaction mean'] > 2.35:
        return 1
    else:
        return 0
    
df['Satif']=df.apply(lambda df:Satif(df),axis=1)

df['Satif']

0       0
1       1
2       1
3       1
4       1
       ..
1465    1
1466    0
1467    1
1468    1
1469    1
Name: Satif, Length: 1470, dtype: int64

In [54]:
df.shape

(1470, 33)

In [55]:
df["JobSatisf mean"]=(df['JobSatisfaction']+df['JobInvolvement'])/2

In [56]:
df.shape

(1470, 34)

In [58]:
def MovingPeople(df):
    if df["NumCompaniesWorked"] > 4:
        return 1
    else:
        return 0
    
    
df["MovingPeople"] = df.apply(lambda df:MovingPeople(df), axis=1)
df["MovingPeople"]

0       1
1       0
2       1
3       0
4       1
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: MovingPeople, Length: 1470, dtype: int64

In [59]:
df.shape

(1470, 35)

In [61]:
def LongDis(df):
    if df['DistanceFromHome'] > 11:
        return 1
    else:
        return 0
    
    
    
df["LongDis"]=df.apply(lambda df:LongDis(df),axis = 1)
df["LongDis"]
        

0       0
1       0
2       0
3       0
4       0
       ..
1465    1
1466    0
1467    0
1468    0
1469    0
Name: LongDis, Length: 1470, dtype: int64

In [63]:
def MiddleTraining(df):
    if df["TrainingTimesLastYear"] >=3 and df["TrainingTimesLastYear"] <= 6:
        return 1
    else:
        return 0
    
    
df['MiddleTraining']=df.apply(lambda df:MiddleTraining(df), axis=1)
df["MiddleTraining"]

0       0
1       1
2       1
3       1
4       1
       ..
1465    1
1466    1
1467    0
1468    1
1469    1
Name: MiddleTraining, Length: 1470, dtype: int64

In [66]:
df["Time_in_each_comp"]=(df['Age']-20)/(df['NumCompaniesWorked']+1)
df["Time_in_each_comp"]

0        2.333333
1       14.500000
2        2.428571
3        6.500000
4        0.700000
          ...    
1465     3.200000
1466     3.800000
1467     3.500000
1468     9.666667
1469     4.666667
Name: Time_in_each_comp, Length: 1470, dtype: float64

In [67]:
df.shape

(1470, 38)

In [68]:
numeric_df=df.select_dtypes(include=[np.number])
categoric_df=df.select_dtypes(exclude=[np.number])

In [73]:
print("Numeric Type : ", numeric_df.columns)
print("\n")
print("Categoric Type : ",categoric_df.columns)

Numeric Type :  Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'TotalSatisfaction mean', 'Satif', 'JobSatisf mean', 'MovingPeople',
       'LongDis', 'MiddleTraining', 'Time_in_each_comp'],
      dtype='object')


Categoric Type :  Index(['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender',
       'JobRole', 'MaritalStatus', 'OverTime'],
      dtype='object')


In [78]:
df=df.drop(['DailyRate','DistanceFromHome','EnvironmentSatisfaction','HourlyRate', 'JobInvolvement','JobSatisfaction','NumCompaniesWorked','RelationshipSatisfaction','TrainingTimesLastYear'],axis=1)

In [79]:
df.shape

(1470, 29)

In [84]:
data=pd.get_dummies(df,columns=categoric_df )

ValueError: Boolean array expected for the condition, not object

In [83]:
data.head()

NameError: name 'data' is not defined